import type { NextPage } from 'next'
import Head from 'next/head'
import { Form, Title } from '../components'
import { useForm } from '../hooks/useForm'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { input, setInput, onChange, onClick } = useForm();
  return (
    <>
      <Head>
        <title>映画検索アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title />
        <Form {...{input, setInput, onChange, onClick}}/>
      </main>

      <footer>
        footer
      </footer>
    </>
  )
}

export default Home
