import type { NextPage } from 'next'
import Head from 'next/head'
import { Books, Form, Title } from '../components'
import { useBooks, useForm } from '../hooks/'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { books, setBooks } = useBooks();
  const { input, setInput, onChange, onClick } = useForm(books, setBooks);
  return (
    <>
      <Head>
        <title>本検索アプリ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Title />
        <Form {...{input, setInput, onChange, onClick}}/>
        <Books {...{books}} />
      </main>

      <footer>

      </footer>
    </>
  )
}

export default Home
